#!/bin/bash

# This must match the install directory
INSTALL=/Users/vipulvpatil/Desktop/Labs/interviewing-practice/Sept2023/Algorithms_Princeton

# Sets the path to the classpath libraries
CLASSPATH=(.:${INSTALL}/jars/algs4.jar)

# Execute with textbook libraries in Java classpath.
java -cp "${CLASSPATH}" "$@"
